# Base image
FROM node:19-alpine

WORKDIR /app
COPY package*.json ./

RUN npm install
COPY . .

RUN npm run build
ENV NODE_ENV=development
ENV PORT=30001

EXPOSE 30001

CMD ["npx", "ts-node","dist/index.d.ts"]
